apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    environment: dev
    project: roboshop
    component: catalogue
data:

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-np
  namespace: roboshop
  labels:
    environment: dev
    project: roboshop
    component: frontend
spec:
  selector:
    environment: dev
    project: roboshop
    component: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      environment: dev
      project: roboshop
      component: frontend
  template:
    metadata:
      labels:
        environment: dev
        project: roboshop
        component: frontend
    spec:
      containers:
        - name: nginx
          image: adarshupputuri/roboshop:frontend
          volumeMounts:
            - name: frontend-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          ports:
            - containerPort: 80
      volumes:
        - name: frontend-config-volume
          configMap:
            name: frontend-configmap
            items:
              - key: nginx.conf
                path: nginx.conf


