apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
  labels:
    environment: dev
    project: roboshop
    component: cart
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
  labels:
    environment: dev
    project: roboshop
    component: cart
spec:
  selector:
    environment: dev
    project: roboshop
    component: cart
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      environment: dev
      project: roboshop
      component: cart
  template:
    metadata:
      labels:
        environment: dev
        project: roboshop
        component: cart
    spec:
      containers:
        - name: cart
          image: adarshupputuri/roboshop:cart
          envFrom:
            - configMapRef:
                name: cart



