apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
  labels:
    environment: dev
    project: roboshop
    component: shipping
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"

---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  labels:
    environment: dev
    project: roboshop
    component: shipping
spec:
  selector:
    environment: dev
    project: roboshop
    component: shipping
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      environment: dev
      project: roboshop
      component: shipping
  template:
    metadata:
      labels:
        environment: dev
        project: roboshop
        component: shipping
    spec:
      containers:
        - name: shipping
          image: adarshupputuri/roboshop:shipping
          envFrom:
            - configMapRef:
                name: shipping



