apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    environment: dev
    project: roboshop
    component: frontend
spec:
  selector:
    environment: dev
    project: roboshop
    component: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      environment: dev
      project: roboshop
      component: mongodb
  template:
    metadata:
      labels:
        environment: dev
        project: roboshop
        component: mongodb
    spec:
      containers:
        - name: mongodb
          image: adarshupputuri/roboshop:mongodb
