apiVersion: v1
kind: Pod
metadata:
  name: roboshop-pod
  namespace: roboshop
  labels:
    environment: dev
    project: roboshop
    poc: roboshop
spec:
  containers:
    - name: roboshop-container
      image: nginx:alpine
      env:
        - name: APP_ENV
          value: dev
        - name: APP_DEBUG
          value: "true"
        - name: APP_PORT
          value: "8080"
