apiVersion: v1
kind: Pod
metadata:
  name: ngnix-env
  namespace: roboshop
  labels:
    environment: dev
    project: roboshop
    poc: roboshop
spec:
  containers:
    - name: nginx-env
      image: nginx:latest
      envFrom:
            - configMapRef:
                name: roboshop-config