apiVersion: v1
kind: Pod
metadata:
    name: nginx-secret
    namespace: roboshop
    labels:
        environment: dev
        project: roboshop
        poc: roboshop
spec:
    containers:
        - name: nginx-secret
          image: nginx:latest
          envFrom:
                - secretRef:
                    name: roboshop-secret