apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    project: myproject
spec:
  selector:
    environment: dev
    project: roboshop
    poc: roboshop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

