apiVersion: apps/v1
kind: Deplopyment
metadata:
  name: frontend-replicaset
  namespace: roboshop
spec:
  replicas: 3
  selector:
    matchLabels:
      environment: dev
      project: roboshop
      tier: frontend
      purpose: deployment
  template:
    metadata:
      labels:
        environment: dev
        project: roboshop
        tier: frontend
        purpose: deployment
    spec:
      containers:
        - name: nginx-frontend
          image: nginx:latest
          ports:
            - containerPort: 80
