apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: roboshop
type: Opaque
data:
  docker-server: "https://index:docker:io/v1/"
  docker-username: "adarshupputuri"
  docker-password: "Adarsh@1365"